"""
Shared helpers for all sub-task generators.

VariantCatalogue is the single source of truth — reads
`env/scripts/seed.json` (the canonical seed for the website's catalogue)
and indexes variants by (category, tier, style). All generators query
this object; nothing else touches the DB or seed file directly.

Style slug mapping is the W1+W5 convention:
  var_a → modern
  var_b → minimalist
  var_c → vintage
  var_d → industrial
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]
SEED_PATH = REPO_ROOT / "env" / "scripts" / "seed.json"
PRICING_PATH = REPO_ROOT / "env" / "scripts" / "pricing_naming.json"

VAR_KEY_TO_STYLE = {
    "var_a": "modern",
    "var_b": "minimalist",
    "var_c": "vintage",
    "var_d": "industrial",
}
STYLE_TO_VAR_KEY = {v: k for k, v in VAR_KEY_TO_STYLE.items()}
ALL_STYLES = ["modern", "minimalist", "vintage", "industrial"]
ALL_TIERS = (1, 2, 3)


# Synthesise the Prisma-style cuid that the seeder *would* produce. The
# real cuid is generated by Prisma at insert time, so we don't have it
# from JSON alone — but the eval orchestrator binds tasks to the actual
# DB by `urlHash` (unique) before each run. Generators output urlHash as
# the stable variant identifier; the variant_id field carries the same
# value as a placeholder until the orchestrator resolves it.

@dataclass(frozen=True)
class Variant:
    # Stable cross-environment id (we use urlHash because it survives reseeds).
    id: str
    url_hash: str
    category_slug: str
    grain_tier: int
    var_key: str            # var_a..d
    style_slug: str         # modern/minimalist/vintage/industrial
    primary_image: str
    title: str              # L2-safe
    alt_text: str
    product_base_name: str
    product_material: str
    sub_page_slug: str
    # W7r2 — collection + pricing + material/color (from pricing_naming.json)
    display_name: str
    color_name: str
    price: float
    collection_slug: str
    collection_name: str
    material_slug: str
    material_descriptor: str
    tier_flavour: str       # premium | mid | budget

    @property
    def category_display(self) -> str:
        return self.category_slug.replace("_", " ").rstrip("s")


@dataclass(frozen=True)
class Category:
    slug: str
    display: str
    description: str


class VariantCatalogue:
    def __init__(self, seed_path: Path = SEED_PATH, pricing_path: Path = PRICING_PATH):
        with open(seed_path, "r") as f:
            data = json.load(f)
        with open(pricing_path, "r") as f:
            pricing = json.load(f)
        nv = pricing["variants"]
        self._categories: list[Category] = []
        self._variants: list[Variant] = []
        # Index structures
        self._by_cat: dict[str, list[Variant]] = {}
        self._by_cat_tier: dict[tuple[str, int], list[Variant]] = {}
        self._by_cat_tier_style: dict[tuple[str, int, str], Variant] = {}
        self._by_id: dict[str, Variant] = {}
        # Collection slug → list of variants
        self._by_collection: dict[str, list[Variant]] = {}

        for cat in data["categories"]:
            self._categories.append(Category(
                slug=cat["slug"],
                display=cat["display"],
                description=cat["description"],
            ))
            for product in cat["products"]:
                for v in product["variants"]:
                    style = VAR_KEY_TO_STYLE.get(v["internalVariantKey"], "unknown")
                    sub_page = v.get("subPageSlug") or style
                    naming = nv.get(v["urlHash"]) or {}
                    variant = Variant(
                        id=v["urlHash"],
                        url_hash=v["urlHash"],
                        category_slug=cat["slug"],
                        grain_tier=v["grainTier"],
                        var_key=v["internalVariantKey"],
                        style_slug=style,
                        primary_image=v["primaryImage"],
                        title=v["title"],
                        alt_text=v["altText"],
                        product_base_name=product["baseName"],
                        product_material=product["material"],
                        sub_page_slug=sub_page,
                        display_name=naming.get("displayName", v["title"]),
                        color_name=naming.get("colorName", ""),
                        price=float(naming.get("price", product["price"])),
                        collection_slug=naming.get("collectionSlug", ""),
                        collection_name=naming.get("collectionName", ""),
                        material_slug=naming.get("materialSlug", ""),
                        material_descriptor=naming.get("materialDescriptor", ""),
                        tier_flavour=naming.get("tierFlavour", "mid"),
                    )
                    self._variants.append(variant)
                    self._by_id[variant.id] = variant
                    self._by_cat.setdefault(cat["slug"], []).append(variant)
                    self._by_cat_tier.setdefault((cat["slug"], variant.grain_tier), []).append(variant)
                    self._by_cat_tier_style[(cat["slug"], variant.grain_tier, style)] = variant
                    if variant.collection_slug:
                        self._by_collection.setdefault(variant.collection_slug, []).append(variant)

    @property
    def categories(self) -> list[Category]:
        return list(self._categories)

    @property
    def variants(self) -> list[Variant]:
        return list(self._variants)

    def by_id(self, urlhash_or_id: str) -> Variant:
        return self._by_id[urlhash_or_id]

    def variants_in(self, category_slug: str) -> list[Variant]:
        return list(self._by_cat.get(category_slug, []))

    def variants_at(self, category_slug: str, tier: int) -> list[Variant]:
        return list(self._by_cat_tier.get((category_slug, tier), []))

    def variant(self, category_slug: str, tier: int, style: str) -> Variant:
        return self._by_cat_tier_style[(category_slug, tier, style)]

    def variant_or_none(self, category_slug: str, tier: int, style: str) -> Optional[Variant]:
        return self._by_cat_tier_style.get((category_slug, tier, style))

    def variants_in_collection(self, collection_slug: str) -> list[Variant]:
        return list(self._by_collection.get(collection_slug, []))

    # ---------- pairing primitives ----------

    def pick_category(self, rng: random.Random, exclude: Iterable[str] = ()) -> Category:
        pool = [c for c in self._categories if c.slug not in set(exclude)]
        return rng.choice(pool)

    def pick_categories(self, rng: random.Random, n: int) -> list[Category]:
        return rng.sample(self._categories, n)

    def pick_style(self, rng: random.Random, exclude: Iterable[str] = ()) -> str:
        pool = [s for s in ALL_STYLES if s not in set(exclude)]
        return rng.choice(pool)

    def pick_tier(self, rng: random.Random) -> int:
        return rng.choice(ALL_TIERS)


# ---------- RNG / helpers ----------

def seeded_rng(seed: int, namespace: str = "task") -> random.Random:
    """Deterministic RNG keyed on (namespace, seed)."""
    h = hashlib.sha256(f"{namespace}|{seed}".encode()).digest()
    rng = random.Random()
    rng.seed(int.from_bytes(h[:8], "big"))
    return rng


def coarse_noun(category_slug: str) -> str:
    """L2-compliant coarse noun used in user utterances."""
    return {
        "vases": "vase",
        "lamps": "lamp",
        "cushions": "cushion",
        "chairs": "chair",
        "rugs": "rug",
        "tables": "side table",
        "sofas": "sofa",
        "bookshelves": "bookshelf",
        "wall_art": "wall print",
        "plant_pots": "plant pot",
    }.get(category_slug, category_slug.replace("_", " ").rstrip("s"))


def style_user_term(style_slug: str) -> str:
    """How a user would refer to a style in chat. Same L2 vocabulary as the sub-page titles."""
    return {
        "modern": "modern",
        "minimalist": "minimalist",
        "vintage": "vintage",
        "industrial": "industrial",
    }[style_slug]


def price_bracket_isolating_pair(
    a: "Variant",
    b: "Variant",
    scope: list["Variant"],
) -> tuple[float, float] | None:
    """Return (low, high) such that **exactly** {a, b} from `scope` have
    `low <= price <= high`. None if no such bracket exists (i.e., another
    `scope` variant has a price strictly between a.price and b.price).

    Bracket boundaries are snapped to ".49" form so they don't accidentally
    coincide with any catalogue price (which use ".99").
    """
    lo_p, hi_p = (a.price, b.price) if a.price <= b.price else (b.price, a.price)
    # Reject if any other product in scope has price ∈ (lo_p, hi_p).
    intruders = [v for v in scope if v.url_hash not in (a.url_hash, b.url_hash)
                 and lo_p < v.price < hi_p]
    if intruders:
        return None
    # Snap the bracket boundaries: low just below a.price, high just above b.price.
    below = sorted([v for v in scope if v.url_hash not in (a.url_hash, b.url_hash)
                    and v.price < lo_p], key=lambda v: v.price)
    above = sorted([v for v in scope if v.url_hash not in (a.url_hash, b.url_hash)
                    and v.price > hi_p], key=lambda v: v.price)
    if below:
        low = (below[-1].price + lo_p) / 2.0
    else:
        low = lo_p - 1.00
    if above:
        high = (hi_p + above[0].price) / 2.0
    else:
        high = hi_p + 1.00
    return (round(low) - 0.51, round(high) - 0.51)


def find_price_adjacent_partner(
    anchor: "Variant",
    candidates: list["Variant"],
    scope: list["Variant"],
) -> "Variant | None":
    """Among `candidates` (must be in `scope`), find one whose price is
    adjacent to `anchor` in `scope` — i.e. there's no third `scope`
    variant whose price lies strictly between anchor and the partner.

    Used to build a tight 2-element bracket containing both anchor and
    partner.
    """
    by_price = sorted(scope, key=lambda v: v.price)
    idx = next((i for i, v in enumerate(by_price) if v.url_hash == anchor.url_hash), -1)
    if idx == -1:
        return None
    neighbours = []
    if idx - 1 >= 0:
        neighbours.append(by_price[idx - 1])
    if idx + 1 < len(by_price):
        neighbours.append(by_price[idx + 1])
    cand_set = {c.url_hash for c in candidates}
    for n in neighbours:
        if n.url_hash in cand_set:
            return n
    return None


def price_cutoff_isolating(target: "Variant", siblings: list["Variant"]) -> float:
    """Pick a "< $X" cut-off such that exactly `target` (and no other sibling
    in the same (cat, tier)) satisfies price < X.

    Uses the price midpoint between target and the next-cheaper sibling
    above it (or 5 cents above target if target is the most expensive).
    """
    # Filter to candidates strictly different from target by urlHash.
    other = [s for s in siblings if s.url_hash != target.url_hash]
    # Among siblings cheaper than target — none should be candidates either,
    # so we need cut-off to exclude them too. Pick X = target.price + 0.50
    # if target is the cheapest; otherwise X = midpoint(target.price, next_above).
    above = sorted([s for s in other if s.price > target.price], key=lambda s: s.price)
    below = [s for s in other if s.price < target.price]
    if below:
        # Below-target siblings would *also* satisfy "< X" unless we phrase
        # the predicate as "<= target.price" or "between L and X". Switch
        # to a between-range predicate in that case.
        return _between_cutoff(target, below, above)
    # No cheaper siblings — simple "< X" works.
    if above:
        x = (target.price + above[0].price) / 2.0
    else:
        x = target.price + 1.00
    return round(x + 0.5) - 0.01  # snap to ".99" form


def _between_cutoff(target, below, above):
    """Helper for the case where there are cheaper siblings; we return a
    single upper bound X but the task generator should pair it with a
    lower bound from `below`'s max price. Caller handles the pair via
    `price_range_isolating()`.

    Returned value is the upper bound only — for backward compat, this
    function is only called when price_range_isolating is desired.
    """
    if above:
        x = (target.price + above[0].price) / 2.0
    else:
        x = target.price + 1.00
    return round(x + 0.5) - 0.01


def price_range_isolating(target: "Variant", siblings: list["Variant"]) -> tuple[float, float]:
    """Return (low, high) such that exactly `target` satisfies low ≤ price ≤ high
    among the (target + siblings) set. Snapped to ".99" boundaries for
    e-commerce feel.
    """
    other = [s for s in siblings if s.url_hash != target.url_hash]
    below = sorted([s for s in other if s.price < target.price], key=lambda s: s.price)
    above = sorted([s for s in other if s.price > target.price], key=lambda s: s.price)
    low = (below[-1].price + target.price) / 2.0 if below else target.price - 1.00
    high = (target.price + above[0].price) / 2.0 if above else target.price + 1.00
    return (round(low + 0.5) - 0.01, round(high + 0.5) - 0.01)
