"""Family-2 (per-product IC) — task schema (design v6).

DESIGN v6 — ONE CUE PER VIEWED PRODUCT (advisor's update).

A v6 Family-2 task is still a linear chain of D sessions. Every product the
agent views in a session already carries a unique visual cue, baked into the
storefront (the website serves `images/with_cue/...`). The agent's browse is
autonomous; which products it sees is unknown ahead of time, so the recall
probes are NOT pre-specified in the task spec — they are FILLED IN AT RUN TIME
from the recorded encoding trajectory (one probe per (at_session, target,
viewed_product)).

Compared to v5 (one online-injected cue per session):
  v5:  |IC| = N            |Q| = N(N-1)/2          n_steps ∝ N(N-1)/2
  v6:  |IC| = k·N          |Q| = k·N(N-1)/2        n_steps ∝ k·N(N-1)/2
where k = distinct products viewed per session (~12 with the comparison-shop
task). Same encoding cost, ~k× more recall evals per chain.

Tasks generated by `tasks/generators/f2_online_ic.py` are J-INDEPENDENT: session
j depends only on (seed, j), so a J=5 task and a J=10 task with the same seed
share sessions 0..4 byte-for-byte.

See doc/f2_task_design_v6.png.
"""
from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, Field, model_validator


class SessionSpec(BaseModel):
    """One session = one short WebArena-style comparison-shopping task (one
    category). Sessions are short (~22-28 steps); the long horizon comes from
    chaining many sessions, not long sessions. v6: NO pre-chosen cue — every
    product the agent views already carries its own baked-in cue."""
    session_idx: int                  # 0 .. D-1
    shopping_list: list[str]          # the ONE category browsed this session (1 elem)
    n_steps: int                      # session length, ~22..28 steps


class RecallProbe(BaseModel):
    """An eval-only recall side-run. From the state at the end of `at_session`,
    the agent must navigate back to the product whose url_hash carries
    `target_cue_id`. Read-only: scored by url_match, does not affect the spine
    or the bank. v6 probes are FILLED AT RUN TIME — one per viewed product, per
    (at_session, target_session) pair."""
    probe_id: str                     # e.g. "s3_r2_p07"
    at_session: int                   # session whose end-state the probe runs from
    target_session: int               # session in which the viewed product was seen
    target_url_hash: str              # the visited product (the recall target)
    target_cue_id: str                # cue baked into that product (from cue_registry)
    target_cue_object: str
    target_cue_color: str
    reach: int                        # at_session - target_session (>= 1)


class RolloutTreeTask(BaseModel):
    """Family-2 task — kept under this name for import stability; it is a
    linear spine of D sessions plus a list of recall probes (filled at run
    time in v6, since which products the agent views is autonomous)."""
    task_id: str
    variant: str = "f2_per_product_ic_v6"
    n_sessions: int                   # D — sessions along the spine
    max_steps_per_session: int
    sessions: list[SessionSpec]
    probes: list[RecallProbe] = Field(default_factory=list)   # filled at run time
    metadata: dict = Field(default_factory=dict)

    @model_validator(mode="after")
    def _shape(self) -> "RolloutTreeTask":
        if len(self.sessions) != self.n_sessions:
            raise ValueError(f"{self.task_id}: {len(self.sessions)} sessions "
                             f"!= n_sessions={self.n_sessions}")
        idxs = [s.session_idx for s in self.sessions]
        if idxs != list(range(self.n_sessions)):
            raise ValueError(f"{self.task_id}: sessions must be 0..D-1 in order")
        for p in self.probes:
            if not (0 <= p.target_session < p.at_session < self.n_sessions):
                raise ValueError(f"{self.task_id}: probe {p.probe_id} bad sessions")
            if p.reach != p.at_session - p.target_session:
                raise ValueError(f"{self.task_id}: probe {p.probe_id} reach mismatch")
        return self

    def session(self, idx: int) -> SessionSpec:
        return self.sessions[idx]

    def probes_at(self, session_idx: int) -> list[RecallProbe]:
        """Probes that run from the end of `session_idx`, ordered by reach."""
        return sorted((p for p in self.probes if p.at_session == session_idx),
                      key=lambda p: p.reach)


# ---------------------------------------------------------------------------
# Disk I/O
# ---------------------------------------------------------------------------

def save_rollout_tree(task: RolloutTreeTask, pool: Path) -> Path:
    pool.mkdir(parents=True, exist_ok=True)
    dst = pool / f"{task.task_id}.json"
    dst.write_text(task.model_dump_json(indent=2))
    return dst


def load_rollout_tree(path: Path) -> RolloutTreeTask:
    return RolloutTreeTask.model_validate_json(Path(path).read_text())
